### ISSUE TITLE
BucketNotEmpty

### ISSUE THREAD

**Issue by Hawki101** [danburtenshaw/s3-website-pr-action#16]
Getting a `BucketNotEmpty: The bucket you tried to delete is not empty`

Assuming it's a stuff up on my behalf?

Log Below:

`with:
    bucket-prefix: dq-app
  env:
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    GITHUB_TOKEN: ***
Bucket Name: dq-app-pr4[3](https://github.com/QueueBar/DQ-App/runs/5371811382?check_suite_focus=true#step:2:3)
Checking environment variables...
Emptying S3 bucket...
Fetching objects...
Deleting objects...
BucketNotEmpty: The bucket you tried to delete is not empty
    at Request.extractError (/home/runner/work/_actions/danburtenshaw/s3-website-pr-action/v2/dist/index.js:7111:35)
    at Request.callListeners (/home/runner/work/_actions/danburtenshaw/s3-website-pr-action/v2/dist/index.js:21886:20)
    at Request.emit (/home/runner/work/_actions/danburtenshaw/s3-website-pr-action/v2/dist/index.js:21858:10)
    at Request.emit (/home/runner/work/_actions/danburtenshaw/s3-website-pr-action/v2/dist/index.js:20836:1[4](https://github.com/QueueBar/DQ-App/runs/5371811382?check_suite_focus=true#step:2:4))
    at Request.transition (/home/runner/work/_actions/danburtenshaw/s3-website-pr-action/v2/dist/index.js:2017[5](https://github.com/QueueBar/DQ-App/runs/5371811382?check_suite_focus=true#step:2:5):10)
    at AcceptorStateMachine.runTo (/home/runner/work/_actions/danburtenshaw/s3-website-pr-action/v2/dist/index.js:13932:12)
    at /home/runner/work/_actions/danburtenshaw/s3-website-pr-action/v2/dist/index.js:13944:10
    at Request.<anonymous> (/home/runner/work/_actions/danburtenshaw/s3-website-pr-action/v2/dist/index.js:20191:9)
    at Request.<anonymous> (/home/runner/work/_actions/danburtenshaw/s3-website-pr-action/v2/dist/index.js:20838:12)
    at Request.callListeners (/home/runner/work/_actions/danburtenshaw/s3-website-pr-action/v2/dist/index.js:2189[6](https://github.com/QueueBar/DQ-App/runs/5371811382?check_suite_focus=true#step:2:6):18) {
  message: 'The bucket you tried to delete is not empty',
  code: 'BucketNotEmpty',
  region: null,
  time: 2022-03-01T0[7](https://github.com/QueueBar/DQ-App/runs/5371811382?check_suite_focus=true#step:2:7):54:56.445Z,
  requestId: 'B4GMC23WNP7W9[8](https://github.com/QueueBar/DQ-App/runs/5371811382?check_suite_focus=true#step:2:8)J4',
  extendedRequestId: '+WyFIURjrQxwSFzG[9](https://github.com/QueueBar/DQ-App/runs/5371811382?check_suite_focus=true#step:2:9)jBG1FRCY+0WfVnzbFUGdaYaAXx+V7qsPvXXpywLNQHSs8mnAV0n3IaCNcM=',
  cfId: undefined,
  statusCode: 409,
  retryable: false,
  retryDelay: [30](https://github.com/QueueBar/DQ-App/runs/5371811382?check_suite_focus=true#step:2:30).593649540480[34](https://github.com/QueueBar/DQ-App/runs/5371811382?check_suite_focus=true#step:2:34)
}`

**Comment by jdortegar** [comment]
Same issue here @danburtenshaw !
